# Site settings

#header-img: "img/green.jpg"
title: 'Welcome To My Homepage' # 你的博客名字，可以定义修订
description: 'Machine Learning Engineer @ Kuaishou' # 一句话描述你的博客
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

# Gems
gems:
  - jekyll-paginate

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

# Links to include in footer navigation
theme: jekyll-theme-cayman
